### ISSUE TITLE
Win下webdriver的疑问

### ISSUE THREAD

**Issue by dabpop139** [HeroadZ/panda-bamboos-rank#1]
webdriver.Chrome('chromedriver.exe')
我在Win7下的执行这个谷歌浏览器崩溃是什么原因呢，你有没有遇到过。
问题和下面的链接差不多
http://stackoverflow.com/questions/34164831/selenium-crashing-chrome-automation-extension-has-crashed

**Comment by HeroadZ** [comment]
@dabpop139 
我并没有遇到这个问题，是一打开就崩溃还是运行了一会？我的环境是win10
可能有以下原因
1.可能你用了一些ide来运行程序，建议直接用cmd运行
2.可能你用管理员权限运行了
3.chromedriver是最新版本吗
4.可能是运行过快，遇到了exception？（可能性比较小）

**Comment by dabpop139** [comment]
> 1.可能你用了一些ide来运行程序，建议直接用cmd运行
> 感谢了，我的情况是这个原因。
